title: Rodolfo Ricardo | Blog
logo: /assets/img/logo.png
description: Estudos, Brain Dumps e Aleatoriedades | Studies, Brain Dump and Randomness
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
